###
GET localhost:8080/level3/movies HTTP/1.1

###
GET localhost:8080/level3/movies/1 HTTP/1.1

###
POST localhost:8080/level3/movies HTTP/1.1
Content-Type: application/json

{
  "title": "Nowy film",
  "director": "Nowy reżyser",
  "year": "2021"
}

###
PUT localhost:8080/level3/movies/1 HTTP/1.1
Content-Type: application/json

{
  "title": "AKTUALIZACJA!",
  "director": "Nowy reżyser",
  "year": "2021"
}

###
DELETE localhost:8080/level3/movies/4 HTTP/1.1

